version: '3.8'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  postgress:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
  redis_data:
